export const types = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',
    START_PRODUCT_DOWNLOAD: 'START_PRODUCT_DOWNLOAD',
    PRODUCT_DOWNLOAD_SUCCESS: 'PRODUCT_DOWNLOAD_SUCCESS',
    PRODUCT_DOWNLOAD_ERROR: 'PRODUCT_DOWNLOAD_ERROR',
    GET_PRODUCT_DELETE: 'GET_PRODUCT_DELETE',
    PRODUCT_DELETED_SUCCESS: 'PRODUCT_DELETED_SUCCESS',
    PRODUCT_DELETED_ERROR: 'PRODUCT_DELETED_ERROR',
    GET_PRODUCT_EDIT: 'GET_PRODUCT_EDIT',
    START_PRODUCT_EDITION: 'START_PRODUCT_EDITION',
    PRODUCT_EDITED_SUCCESS: 'PRODUCT_EDITED_SUCCESS',
    PRODUCT_EDITED_ERROR: 'PRODUCT_EDITED_ERROR',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT'
}